### ISSUE TITLE
Problem creating Home Assistant Infinitive climate entity

### ISSUE THREAD

**Issue by mglaser1001** [gogades/hass-infinitive#18]
I have Infinitive installed and configured, but when restarting see the error below and the climate entity is not created. Any thoughts?

Running an older version of HA:
Home Assistant 2023.6.3
Supervisor 2024.06.2
Operating System 10.4
Frontend 20230608.0 - latest

Infinitive is installed through HACS and visible. 

My configuration.yaml includes:
climate:
- platform: infinitive
   host: 192.168.1.84
   port: 8080

When restarting HA, I receive the following error in the log file:

Error adding entities for domain climate with platform infinitive
7:46:18 PM – (ERROR) Climate (custom integration) - message first occurred at 7:46:18 PM and shows up 2 times

And the error details are below:
Logger: homeassistant.components.climate
Source: custom_components/infinitive/climate.py:220
Integration: Climate (documentation, issues)
First occurred: 7:46:18 PM (2 occurrences)
Last logged: 7:46:18 PM

Error adding entities for domain climate with platform infinitive
Error while setting up infinitive platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 661, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 282, in capability_attributes
    data[ATTR_PRESET_MODES] = self.preset_modes
                              ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/infinitive/climate.py", line 228, in preset_modes
    _LOGGER.debug("Preset Mode: " + str(self.preset_mode))
                                        ^^^^^^^^^^^^^^^^
  File "/config/custom_components/infinitive/climate.py", line 220, in preset_mode
    if self._status["hold"] is True:
       ~~~~~~~~~~~~^^^^^^^^
KeyError: 'hold'

**Comment by mglaser1001** [comment]
Revolved - first upgrade HA.
